import {z} from 'genkit';

// Wellness Tips Schemas
export const WellnessTipsInputSchema = z.object({
  species: z.enum(['dog', 'cat']).describe('The species of the pet (dog or cat).'),
});
export type WellnessTipsInput = z.infer<typeof WellnessTipsInputSchema>;

const WellnessTipSchema = z.object({
  title: z.string().describe('The title of the wellness tip.'),
  description: z.string().describe('The detailed description of the tip, providing actionable advice.'),
});

export const WellnessTipsOutputSchema = z.object({
  tips: z
    .array(WellnessTipSchema)
    .min(4)
    .max(6)
    .describe('A list of 4 to 6 wellness tips for the specified pet species.'),
});
export type WellnessTipsOutput = z.infer<typeof WellnessTipsOutputSchema>;


// Nutrition Analysis Schemas
export const NutritionAnalysisInputSchema = z.object({
  ingredientsText: z.string().describe("The list of ingredients from the pet food label."),
  age: z.number().describe("The pet's age in years."),
  species: z.enum(['dog', 'cat']).describe("The species of the pet (dog or cat)."),
});
export type NutritionAnalysisInput = z.infer<typeof NutritionAnalysisInputSchema>;

export const NutritionAnalysisOutputSchema = z.object({
  analysis: z.string().describe('A detailed nutritional analysis based on FEDIAF guidelines.'),
});
export type NutritionAnalysisOutput = z.infer<typeof NutritionAnalysisOutputSchema>;

// Enrichment Plan Schemas
export const EnrichmentPlanInputSchema = z.object({
  housingType: z.enum(['apartment', 'house']).describe('The type of housing the pet lives in.'),
  breed: z.string().describe('The breed of the pet.'),
  age: z.number().describe('The age of the pet in years.'),
  animalName: z.string().describe('The name of the pet.'),
  species: z.enum(['dog', 'cat']).describe('The species of the pet.'),
});
export type EnrichmentPlanInput = z.infer<typeof EnrichmentPlanInputSchema>;

export const EnrichmentPlanOutputSchema = z.object({
  plan: z.string().describe('A single, actionable enrichment activity suggestion to reduce stress and boredom.'),
});
export type EnrichmentPlanOutput = z.infer<typeof EnrichmentPlanOutputSchema>;

// Prevention Assistant Schemas
export const PreventionAdviceInputSchema = z.object({
  sex: z.enum(['male', 'female']).describe('The sex of the pet.'),
  age: z.number().describe('The age of the pet in years.'),
  sterilized: z.boolean().describe('Whether the pet is sterilized.'),
});
export type PreventionAdviceInput = z.infer<typeof PreventionAdviceInputSchema>;

export const PreventionAdviceOutputSchema = z.object({
  advice: z.string().describe('The preventive advice generated by the AI.'),
  needsAction: z.boolean().describe('Whether the advice suggests a specific action, like consulting a vet.')
});
export type PreventionAdviceOutput = z.infer<typeof PreventionAdviceOutputSchema>;
